<?php

/**
 *
 * User: zhouyouth
 * Date: 2017/3/27
 * Time: 10:29
 */

class SystemController extends ApiController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        return false;
    }

    //消息中心列表
    public function messageCenterAction(){

        $params = array();
        $params['page'] = $this->get("page");
        $params['pageSize'] = $this->get("pageSize");
        $page = !empty($params["page"]) ? $params["page"] : 1;
        $pageSize = !empty($params["pageSize"]) ? $params["pageSize"] : 10;
        $where = "msg_type=1 ";
        if($this->user_id){
            $where .= " OR reciver='".$this->user_id."'";
        }
        $start = ($page - 1) * $pageSize;
        $count = SystemModel::getmessageCenter($start, $pageSize, $where, true);
        $field = "id,title,content,msg_type,FROM_UNIXTIME(create_time,'%Y/%m/%d') as create_time,msg_status,image_url,url";
        $messageList = SystemModel::getmessageCenter($start, $pageSize,  $where,false,$field);
        if ($messageList) {
            $code = 1000;
            $data = array(
                "count" => $count,
                "thisPage" => $page,
                "pageSize" => $pageSize,
                "countPage" => ceil($count / $pageSize),
                "messageList" => $messageList,
            );
            $this->apiReturn($data, $code);
        } else {
            $code = 1004;
            $data = array(
                "count" => $count,
                "thisPage" => $page,
                "pageSize" => $pageSize,
                "countPage" => ceil($count / $pageSize),
                "messageList" => array(),
            );
            $mag = "消息为空";
            $this->apiReturn($data, $code,$mag);
        }

    }
}